### ISSUE TITLE
Implement root CA (blockchain/ethereum level) 

### ISSUE THREAD

**Issue by Sameow** [LifeBlock/LifeBlock#7]

**Comment by Sameow** [comment]
Use the common account to use the service (from common address) => FAANG to help ppl who cant use metamask to post to implement these interactions 
FAANG to also help to upload to guest account ⇒ Fang will have a guest account  
FAANG will upload on behalf after you submit to them

**Comment by zonestealth** [comment]
I think that FAANG should be the only ones given the unique address which will be more credible for the interactions

**Comment by Sameow** [comment]
Ok the use case goes like this.

1, A business that doesn't want to use blockchain goes to meet FAANG directly.
2. FAANG will use its Lifeblock account to create the interaction on behalf of the SME.

So don't need to implement root CA? @auskure @huangmingg
